-- CFMS Lab / KIT_sodi Supabase schema
-- Run this first in Supabase SQL Editor for a new project.
-- Then run enable_rls_cfms.sql to apply public/authenticated access rules.

create table if not exists public.papers (
  "ID" bigint generated by default as identity primary key,
  "CATEG" text,
  "PrintStatus" integer not null default 1,
  "AUTHORS" text,
  "TITLE" text,
  "JOURNAL_NAME" text,
  "VOLUME" text,
  "PAGE" text,
  "P_YEAR" integer,
  "P_MONTH" integer,
  "P_DAY" integer,
  "DOI" text,
  "PDF" text,
  "FUNDING" text,
  "MEMO" text,
  "COUNTRY" text,
  "SCISTATUS" integer,
  "SCIFACTOR" text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tt_courses (
  id bigint generated by default as identity primary key,
  semester text not null,
  "sClassProfName" text,
  "sClassYear" text,
  "sClassName" text,
  "sClassDay" text,
  "sClassTime" text,
  "sClassRoom" text,
  "sClassType" text,
  created_at timestamptz not null default now()
);

create table if not exists public.tt_professors (
  id bigint generated by default as identity primary key,
  semester text not null,
  "sProfName" text,
  "sProfColor" text,
  created_at timestamptz not null default now()
);

create table if not exists public.tt_rooms (
  id bigint generated by default as identity primary key,
  semester text not null,
  "sRoomName" text,
  created_at timestamptz not null default now()
);

create table if not exists public.jobgis_jobs (
  id bigint generated by default as identity primary key,
  "sStudentDpt" text,
  "sStudentYear" text,
  "sStudentName" text,
  "sStudentGrade" text,
  "sStudentTOEIC" text,
  "sOfficeName" text,
  "sOfficeType" text,
  "sOfficeSalary" text,
  "sOfficeURL" text,
  "sOfficeAddress" text,
  "sOfficeLng" text,
  "sOfficeLat" text,
  created_at timestamptz not null default now()
);

create table if not exists public.jobgis_office_types (
  id bigint generated by default as identity primary key,
  "sOfficeType" text not null,
  "sOfficeSymbol" text,
  created_at timestamptz not null default now(),
  unique ("sOfficeType")
);

create table if not exists public.mindmaps (
  id text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

-- graph.html / mindmap.html / upjuk.html 공유 프로젝트 노드 (자세한 설명: schema_project_nodes.sql)
create table if not exists public.project_nodes (
  id text primary key,
  mindmap_id text,
  title text,
  grade text,
  status text,
  badge text,
  grade_note text,
  bottleneck text,
  brief text,
  note text,
  url text,
  project_path text,
  pos_x integer,
  pos_y integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace view public.jobgis_jobs_public as
select
  id,
  "sStudentDpt",
  "sStudentYear",
  'OOO'::text as "sStudentName",
  "sStudentGrade",
  "sStudentTOEIC",
  "sOfficeName",
  "sOfficeType",
  "sOfficeSalary",
  "sOfficeURL",
  "sOfficeAddress",
  "sOfficeLng",
  "sOfficeLat",
  created_at
from public.jobgis_jobs;

create index if not exists papers_year_idx on public.papers ("P_YEAR" desc);
create index if not exists papers_categ_idx on public.papers ("CATEG");
create index if not exists tt_courses_semester_idx on public.tt_courses (semester);
create index if not exists tt_professors_semester_idx on public.tt_professors (semester);
create index if not exists tt_rooms_semester_idx on public.tt_rooms (semester);
create index if not exists jobgis_jobs_office_type_idx on public.jobgis_jobs ("sOfficeType");
create index if not exists project_nodes_grade_idx on public.project_nodes (grade);
create index if not exists project_nodes_mindmap_idx on public.project_nodes (mindmap_id);

insert into storage.buckets (id, name, public)
values ('pdfs', 'pdfs', false)
on conflict (id) do update set public = false;
